### ISSUE TITLE
 The box is degenerate on x

### ISSUE THREAD

**Issue by ziceptor** [Ewoutvans/GameKow#1]
When you click on the text "save"
https://gist.github.com/ziceptor/30836d041f7aee506f610e17e1560acb

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar

The difficulties of translation. Could you point to the scheme where:
CORNER_PLAY_1
CORNER_PLAY_2
CORNER_AREA_1
CORNER_AREA_2

**Comment by Ewoutvans** [comment]
This is fixed now
